#!/usr/bin/env bash
# this script installs nginx with configuration

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart
