#!/usr/bin/env bash
# this script installs nginx with configuration

apt update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "44a error_page 404 /custom_404.html; location = /custom_404.html {\nroot /var/www/html/;\ninternal;\n}" /etc/nginx/sites-available/default
service nginx restart
