#!/usr/bin/env bash
# this script installs nginx with configuration

sudo apt update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i '36a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "44a error_page 404 /custom_404.html; location = /custom_404.html { root /var/www/html/;internal;}" /etc/nginx/sites-available/default
sudo service nginx restart
