#!/usr/bin/env bash
# this script installs nginx with configuration

sudo apt-get update
sudo apt-get -y install nginx
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" > sudo tee /var/www/html/404.html
sed -i "44a error_page 404 /custom_404.html; location = /custom_404.html { root /var/www/html/;internal;}" /etc/nginx/sites-available/default
sudo service nginx restart
