#!/usr/bin/env bash
# this script needs notes
sudo apt-get intall -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy
echo -e " \
frontend front_server
        bind *:80
        mode http
        default_backend back_server

backend back_server
        mode http
        balance roundrobin
        server 1698-web-01 35.196.13.145:80
        server 1698-web-02 184.72.66.167:80" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
