#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get -y install haproxy
echo -e "\nlisten firstbalance\n\tbind *:80\n\tbalance roundobin\n\toption forwardfor\n\tserver 1698-web-01 35.196.13.145:80\n\tserver 1698-web-02 184.72.66.167:80" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
