#!/usr/bin/env bash
# this script debugs server ensuring listening on port 80
sudo service nginx stop
sudo rm /etc/nginx/sites-enabled/default
kill -9 "$(pgrep -ef | grep 'nginx' | awk '{print $2}')"
sudo service nginx restart
