#!/usr/bin/env bash
# this script displays list of currently running processes
# all processes for all users, including those not having TTY
# display in user-oriented format - show process hierarchy
ps -U root -u root u
