#!/usr/bin/env bash
# this script displays FizzBuzz
i=0
while [[ $i -lt 100 ]]
do
    ((i++))
    if ! ((i%15)); then
	echo FizzBuzz
    elif ! ((i%5)); then
	echo Buzz
    elif ! ((i%3)); then
	echo Fizz
    else
	echo $i
    fi
done
