#!/usr/bin/env bash
# this script loops from 1..10 displays given
i=1
for i in {1..10}
do
if [ $i == 4 ]; then
   echo "bad luck"
elif [ $i == 8 ]; then
   echo "good luck"
else
    echo "Holberton School"
fi
done
