#!/usr/bin/env bash
# this script checks for file existence and content
if [ -e "holbertonschool" ]
then
    echo "holbertonschool file exists"
if [ -s "holbertonschool" ]
then
    echo "holbertonschool file is not empty"
else
    echo "holbertonschool file is empty"
fi

if [ -f "holbertonschool" ]
    then
	echo "holbertonschool is a regular file"
    fi
else
    echo "file does not exist"
fi
