#!/usr/bin/env bash
# this script configures localhost IP address and facebook.com IP address
cp /etc/hosts ~hosts.new
echo "127.0.0.2      localhost" ~hosts.new
echo "8.8.8.8        facebook.com" >> ~hosts.new
cp -f ~/hosts.new /etc/hosts
